### ISSUE TITLE
Runtime error for list of size 6, target group size 4

### ISSUE THREAD

**Issue by stellanor** [toreyhickman/garoupa#1]
Hi @toreyhickman !

I found a bug in garoupa where it will raise a runtime error when asked to form a group out of six elements, with a target size of 4 and a max difference of 1.

I tried to generalize the problem as `failure_case_size = 2 * (target_size - max_difference)` but couldn't repeat that with other target sizes.

Here's some test output:

```
2.3.0 :003 > require 'garoupa'
 => true 
2.3.0 :004 > Garoupa.make_groups(["one", "two", "three", "four", "five", "six"], target_size: 4, max_difference: 1)
NoMethodError: undefined method `<<' for nil:NilClass
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:73:in `block in disperse_last_group'
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `each'
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `each_with_index'
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `disperse_last_group'
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:59:in `correct_for_group_size_difference'
	from /Users/elliepoley/.rvm/gems/ruby-2.3.0/gems/garoupa-1.0.1/lib/garoupa.rb:11:in `make_groups'
	from (irb):4
	from /Users/elliepoley/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'

2.3.0 :005 > Garoupa.make_groups(["one", "two", "three", "four", "five", "six", "seven"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803c33bc88 @groups=[["five", "three", "four", "seven"], ["two", "one", "six"]], @list=["one", "two", "three", "four", "five", "six", "seven"], @past_groupmates={"one"=>[], "two"=>[], "three"=>[], "four"=>[], "five"=>[], "six"=>[], "seven"=>[]}> 
2.3.0 :006 > Garoupa.make_groups(["one", "two", "three", "four", "five"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803d087a68 @groups=[["one", "five", "four", "three", "two"]], @list=["one", "two", "three", "four", "five"], @past_groupmates={"one"=>[], "two"=>[], "three"=>[], "four"=>[], "five"=>[]}> 
2.3.0 :007 > Garoupa.make_groups(["one", "two", "three", "four"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803d09cbe8 @groups=[["three", "four", "two", "one"]], @list=["one", "two", "three", "four"], @past_groupmates={"one"=>[], "two"=>[], "three"=>[], "four"=>[]}> 
2.3.0 :008 > Garoupa.make_groups(["one", "two", "three"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803c33a8b0 @groups=[["one", "three", "two"]], @list=["one", "two", "three"], @past_groupmates={"one"=>[], "two"=>[], "three"=>[]}> 
2.3.0 :009 > Garoupa.make_groups(["one", "two"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803c311f00 @groups=[["two", "one"]], @list=["one", "two"], @past_groupmates={"one"=>[], "two"=>[]}> 
2.3.0 :010 > Garoupa.make_groups(["one"], target_size: 4, max_difference: 1)
 => #<Garoupa:0x007f803d872340 @groups=[["one"]], @list=["one"], @past_groupmates={"one"=>[]}> 
```

**Comment by toreyhickman** [comment]
Hi, @stellanor.  Thanks for the issue.

I took a quick peek at the code, and it looks like this error would occur when there are less groups of the desired size than items that need to be dispersed.

So, if making groups of four out of six items, there would be only one group of the desired size, but two items to be dispersed.  The dispersion is done by index in the group to be dispersed, so the first item to be dispersed would go to desired-size group 0.  The second would go to desired-size group 1, which doesn't exist.

I suppose I could find an alternative way of finding the group into which the item is dispersed, like a group with the least number of items.  But, in this case, that would result in one group of six.  I wonder if that would be more inline with expectations than reverting to two groups of three.

**Comment by toreyhickman** [comment]
I was able to recreate the error using 13 items with a target group size of 5 and a max difference of 1.  This leads to two groups of five with three items to disperse (i.e., more items to disperse than target-sized groups), and the error occurs when trying to disperse the third item.

```
2.2.1 :001 > require 'garoupa'
 => true 
2.2.1 :002 > Garoupa.make_groups([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], target_size: 5, max_difference: 1)
NoMethodError: undefined method `<<' for nil:NilClass
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:73:in `block in disperse_last_group'
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `each'
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `each_with_index'
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:72:in `disperse_last_group'
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:59:in `correct_for_group_size_difference'
	from /Users/Torey/.rvm/gems/ruby-2.2.1/gems/garoupa-1.0.1/lib/garoupa.rb:11:in `make_groups'
	from (irb):2
	from /Users/Torey/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```
